export type Level = "منخفض" | "متوسط" | "عالٍ" | "عالية" | "عالية جدًا" | "منخفضة" | "متوسطة";

export interface Suggestion {
  id: string;
  sectionId: string;
  title: string;
  value: Level;
  complexity: Level;
  priority: Level;
  phase: string;
  rationale: string;
  benefit: string;
}

export const SUGGESTIONS: Suggestion[] = [
  {
    id: "sg-appointment-booking",
    sectionId: "patient-journey",
    title: "حجز موعد سحب العينة أونلاين",
    value: "عالية",
    complexity: "متوسط",
    priority: "عالية",
    phase: "المرحلة الثانية",
    rationale: "يقلل الازدحام والانتظار في الاستقبال ويوزّع الحجوزات على اليوم.",
    benefit: "تجربة أسرع للمريض وتقليل الضغط على الفرع في أوقات الذروة.",
  },
  {
    id: "sg-sms-fallback",
    sectionId: "whatsapp",
    title: "إشعار SMS احتياطي عند تعذّر واتساب",
    value: "متوسطة",
    complexity: "منخفض",
    priority: "متوسطة",
    phase: "المرحلة الثانية",
    rationale: "ليس كل مريض لديه واتساب فعّال دائمًا أو قد يحظر الرقم.",
    benefit: "ضمان وصول إشعار جاهزية النتيجة لأكبر شريحة ممكنة من المرضى.",
  },
  {
    id: "sg-doctor-portal",
    sectionId: "patient-portal",
    title: "بوابة أطباء لعرض نتائج مرضاهم المُحالين",
    value: "عالية",
    complexity: "عالٍ",
    priority: "متوسطة",
    phase: "المرحلة الثالثة",
    rationale: "يقوّي علاقة المعمل بالأطباء المُحيلين ويسهّل عليهم المتابعة.",
    benefit: "ولاء أكبر من الأطباء المُحيلين وزيادة تدفّق الإحالات للمعمل.",
  },
  {
    id: "sg-critical-alert-doctor",
    sectionId: "ai",
    title: "تنبيه فوري للطبيب المعالج عند نتيجة حرجة",
    value: "عالية جدًا",
    complexity: "متوسط",
    priority: "عالية",
    phase: "المرحلة الأولى",
    rationale: "نتيجة حرجة قد تحتاج تدخلًا طبيًا سريعًا ولا يجب انتظار مراجعة المريض للنتيجة بنفسه.",
    benefit: "سلامة أعلى للمريض وتقليل المخاطر والمسؤولية القانونية عن التأخير.",
  },
  {
    id: "sg-home-collection",
    sectionId: "patient-journey",
    title: "خدمة سحب عينة منزلي مع تتبّع المندوب",
    value: "عالية",
    complexity: "عالٍ",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "طلب متزايد من كبار السن وأصحاب الهمم والعملاء المشغولين.",
    benefit: "توسيع قاعدة العملاء وميزة تنافسية واضحة عن المعامل المجاورة.",
  },
  {
    id: "sg-recurring-packages",
    sectionId: "solution",
    title: "باقات فحص دوري مع تذكير تلقائي سنوي",
    value: "عالية",
    complexity: "منخفض",
    priority: "عالية",
    phase: "المرحلة الثانية",
    rationale: "يحوّل زيارة المريض من '​عند المرض' إلى فحص وقائي دوري منظّم.",
    benefit: "إيراد متكرر للمعمل وولاء طويل المدى من العملاء.",
  },
  {
    id: "sg-branch-kpi",
    sectionId: "admin-dashboard",
    title: "لوحة مقارنة أداء الفروع (KPI تنفيذي)",
    value: "عالية",
    complexity: "متوسط",
    priority: "متوسطة",
    phase: "المرحلة الثانية",
    rationale: "الإدارة العامة تحتاج نظرة موحّدة على أداء كل فرع لاتخاذ قرارات سريعة.",
    benefit: "قرارات إدارية أسرع وأدق مبنية على بيانات حية لا تقديرات.",
  },
  {
    id: "sg-satisfaction-survey",
    sectionId: "reports",
    title: "استبيان رضا قصير بعد كل زيارة",
    value: "متوسطة",
    complexity: "منخفض",
    priority: "متوسطة",
    phase: "المرحلة الثانية",
    rationale: "قياس جودة الخدمة من منظور المريض مباشرة وبشكل مستمر.",
    benefit: "تحسين مستمر لتجربة العميل بناءً على ملاحظات حقيقية.",
  },
  {
    id: "sg-2fa",
    sectionId: "security",
    title: "مصادقة ثنائية (2FA) لحسابات المراجع والاعتماد الطبي",
    value: "عالية جدًا",
    complexity: "متوسط",
    priority: "عالية",
    phase: "المرحلة الأولى",
    rationale: "حسابات اعتماد النتائج حسّاسة قانونيًا وطبيًا وتحتاج طبقة حماية إضافية.",
    benefit: "حماية أقوى من اختراق الحسابات القادرة على اعتماد نتائج المرضى.",
  },
  {
    id: "sg-sample-archive",
    sectionId: "windows-app",
    title: "أرشفة رقمية لموقع حفظ العينة الفيزيائية",
    value: "متوسطة",
    complexity: "متوسط",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "يسهّل إعادة الفحص أو المراجعة على نفس العينة عند الحاجة.",
    benefit: "تتبع دقيق للعينات وتقليل فرص فقدانها أو خلطها.",
  },
  {
    id: "sg-bilingual",
    sectionId: "patient-portal",
    title: "دعم واجهة ثنائية اللغة (عربي / إنجليزي)",
    value: "متوسطة",
    complexity: "متوسط",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "خدمة شريحة المقيمين والجاليات غير الناطقة بالعربية.",
    benefit: "توسيع قاعدة العملاء المحتملين دون تغيير جوهر النظام.",
  },
  {
    id: "sg-archival-pdf",
    sectionId: "patient-portal",
    title: "تصدير تقرير PDF منظّم وقابل للأرشفة الطبية",
    value: "متوسطة",
    complexity: "منخفض",
    priority: "متوسطة",
    phase: "المرحلة الثانية",
    rationale: "يسهّل قبول التقرير رسميًا لدى مستشفيات أو جهات تأمين أخرى.",
    benefit: "مصداقية أعلى للتقرير الرقمي الصادر من المعمل.",
  },
  {
    id: "sg-whatsapp-chatbot",
    sectionId: "whatsapp",
    title: "Chatbot أساسي على واتساب للاستفسارات العامة",
    value: "متوسطة",
    complexity: "متوسط",
    priority: "متوسطة",
    phase: "المرحلة الثالثة",
    rationale: "يقلل الاتصالات المتكررة لنفس الأسئلة (المواعيد، الأسعار، الفروع).",
    benefit: "تفريغ وقت فريق الاستقبال للتركيز على مهام أهم.",
  },
  {
    id: "sg-campaign-analytics",
    sectionId: "admin-dashboard",
    title: "تحليلات أداء حملات واتساب التسويقية",
    value: "متوسطة",
    complexity: "متوسط",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "لا قيمة حقيقية لحملة تسويقية دون قياس أثرها الفعلي.",
    benefit: "قرارات تسويقية مبنية على بيانات استجابة حقيقية لا تخمين.",
  },
  {
    id: "sg-temporary-permissions",
    sectionId: "permissions",
    title: "صلاحيات مؤقتة تنتهي تلقائيًا",
    value: "متوسطة",
    complexity: "منخفض",
    priority: "متوسطة",
    phase: "المرحلة الثانية",
    rationale: "موظفو التغطية المؤقتة أو التدريب لا يحتاجون صلاحية دائمة.",
    benefit: "تقليل الثغرات الأمنية الناتجة عن صلاحيات منسية طويلة الأمد.",
  },
  {
    id: "sg-audit-trail",
    sectionId: "security",
    title: "سجل تدقيق كامل وقابل للتصدير لكل مستخدم",
    value: "عالية",
    complexity: "متوسط",
    priority: "عالية",
    phase: "المرحلة الأولى",
    rationale: "مطلوب للمساءلة الطبية والقانونية عند أي استفسار أو نزاع.",
    benefit: "شفافية كاملة وثقة تنظيمية أعلى في النظام.",
  },
  {
    id: "sg-inventory-alert",
    sectionId: "test-catalog",
    title: "تنبيه عند اقتراب نفاد مخزون تحليل شائع",
    value: "متوسطة",
    complexity: "متوسط",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "ربط الكتالوج بالمخزون يمنع توقف تحليل مفاجئ بسبب نفاد الكواشف.",
    benefit: "استمرارية الخدمة دون انقطاع غير متوقع.",
  },
  {
    id: "sg-guardian-auto",
    sectionId: "patient-accounts",
    title: "إدارة تلقائية لحساب 'ولي الأمر' حتى سن معينة",
    value: "عالية",
    complexity: "متوسط",
    priority: "عالية",
    phase: "المرحلة الأولى",
    rationale: "كثير من المرضى أطفال لا يملكون رقم هاتف مستقل لتفعيل حساب.",
    benefit: "تجربة عائلية متكاملة وثقة أعلى من أولياء الأمور.",
  },
  {
    id: "sg-monthly-impact-report",
    sectionId: "reports",
    title: "تقرير مقارنة قبل/بعد يُصدَّر تلقائيًا كل شهر للإدارة",
    value: "متوسطة",
    complexity: "منخفض",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "يوثّق الأثر الفعلي للمشروع بأرقام دورية بدل انطباع عام.",
    benefit: "إثبات ملموس لقيمة الاستثمار في المشروع عبر الزمن.",
  },
  {
    id: "sg-presentation-mode",
    sectionId: "design-directions",
    title: "وضع 'عرض تقديمي' مختصر لهذه الصفحة نفسها",
    value: "منخفضة",
    complexity: "منخفض",
    priority: "منخفضة",
    phase: "المرحلة الثالثة",
    rationale: "يفيد عند عرض المشروع سريعًا في اجتماع قصير مع أطراف أخرى.",
    benefit: "توفير وقت العرض دون فقدان الفكرة العامة للمشروع.",
  },
];

export function getSuggestionsForSection(sectionId: string): Suggestion[] {
  return SUGGESTIONS.filter((s) => s.sectionId === sectionId);
}
